version: "3.8"

services:

  web:
    build: ./frontend
    ports:
      - 80:80
    restart: unless-stopped

  api:
    depends_on:
      - db
    build: ./backend
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      NODE_ENV: production
      JWT_SECRET: xyrax!@123
      MONGO_URL: mongodb://db/devlinks
      CLOUDINARY_NAME: dgzvju87l
      CLOUDINARY_KEY: 511391632166557
      CLOUDINARY_SECRET: 89aMOnXAKNluoBMPHVcCEtSzEPA
    restart: unless-stopped

  db:
    image: mongo:6.0.11-jammy
    ports:
      - 27017:27017
    volumes:
      - devlinks:/data/db
    restart: unless-stopped

volumes:
  devlinks:
