version: "3.8"

services:

  web:
    image: codechd/link-sharing-app-web:3
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - frontend-dist:/usr/share/nginx/html

  api:
    depends_on:
      - db
    image: codechd/link-sharing-app-api:3
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      NODE_ENV: production
      JWT_SECRET: YOUR_JWT_SECRET
      MONGO_URL: mongodb://db/devlinks
      CLOUDINARY_NAME: YOUR_CLOUDINARY_NAME
      CLOUDINARY_KEY: YOUR_CLOUDINARY_KEY
      CLOUDINARY_SECRET: YOU_CLOUDINARY_SECRET
    restart: unless-stopped
    volumes:
      - frontend-dist:/backend/frontend-dist

  db:
    image: mongo:6.0.11-jammy
    ports:
      - 27017:27017
    volumes:
      - devlinks:/data/db
    restart: unless-stopped

volumes:
  devlinks:
  frontend-dist:
